Fix single-agent template generator for skrl's AMP algorithm (#6190)
# Description

Fix single-agent template generator for skrl's AMP algorithm

Fixes # (issue)

```
  File "C:\IsaacLab\source\isaaclab_tasks\isaaclab_tasks\utils\sim_launcher.py", line 441, in launch_simulation
    yield
  File "C:\IsaacLab\scripts\reinforcement_learning\skrl\train.py", line 230, in main
    runner = Runner(env, agent_cfg)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\env_isaaclab\Lib\site-packages\skrl\utils\runner\torch\runner.py", line 41, in __init__
    self._trainer = self._generate_trainer(self._env, copy.deepcopy(self._cfg), self._agent)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\env_isaaclab\Lib\site-packages\skrl\utils\runner\torch\runner.py", line 520, in _generate_trainer
    return self._component(trainer_class)(env=env, agents=agent, cfg=trainer_cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\env_isaaclab\Lib\site-packages\skrl\trainers\torch\sequential.py", line 53, in __init__
    self.agents.init(trainer_cfg=self.cfg)
  File "C:\env_isaaclab\Lib\site-packages\skrl\agents\torch\amp\amp.py", line 234, in init
    self.motion_dataset.add_samples(observations=self.collect_reference_motions(self.cfg.amp_batch_size))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\env_isaaclab\Lib\site-packages\skrl\utils\runner\torch\runner.py", line 464, in <lambda>
    "collect_reference_motions": lambda num_samples: env.collect_reference_motions(num_samples),
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\env_isaaclab\Lib\site-packages\skrl\envs\wrappers\torch\base.py", line 44, in __getattr__
    raise AttributeError(
AttributeError: Wrapped environment (BugVtc6001Env) does not have attribute 'collect_reference_motions'
```

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read and understood the [contribution
guidelines](https://isaac-sim.github.io/IsaacLab/main/source/refs/contributing.html)
- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with
`./isaaclab.sh --format`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [ ] I have updated the changelog and the corresponding version in the
extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already
exists there

<!--
As you go through the checklist above, you can mark something as done by
putting an x character in it

For example,
- [x] I have done this task
- [ ] I have not done this task
-->