Moves h5py import to be lazy to avoid DLL issues in windows (#5682)
# Description

Observation:
Facing error ImportError: DLL load failed while importing defs: The
specified procedure could not be found. while inferencing for task
Isaac-Velocity-Rough-v0

Training for the same task seems to go fine

Command:
isaaclab.bat -p -u code_coverage.py
scripts/reinforcement_learning/skrl/play.py --task
Isaac-Velocity-Rough-Anymal-C-Direct-v0 --visualizer kit


Error Logs:
```
  File "c:/automation/isaac_lab/source/isaaclab/isaaclab/utils/datasets/hdf5_dataset_file_handler.py", line 12, in <module>
    import h5py
  File "C:\automation\uv\sim_6.0.0rc47_lab_0609d56_uv\Lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\automation\uv\sim_6.0.0rc47_lab_0609d56_uv\Lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.
2026-05-18T09:52:22Z [479,504ms] [Warning] [omni.usd] Unexpected reference count of 2 for UsdStage 'anon:000001ECC7B47500:World0.usd' while being closed in UsdContext (this may indicate it is still resident in memory).
[479.997s] Simulation App Shutting Down
```

## Type of change

<!-- As you go through the list, delete the ones that are not
applicable. -->

- Bug fix (non-breaking change which fixes an issue)


## Checklist

- [x] I have read and understood the [contribution
guidelines](https://isaac-sim.github.io/IsaacLab/main/source/refs/contributing.html)
- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with
`./isaaclab.sh --format`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [ ] I have updated the changelog and the corresponding version in the
extension's `config/extension.toml` file
- [ ] I have added my name to the `CONTRIBUTORS.md` or my name already
exists there

<!--
As you go through the checklist above, you can mark something as done by
putting an x character in it

For example,
- [x] I have done this task
- [ ] I have not done this task
-->